# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
 xcodeproj 'ByteDanceCampus_Klotski.xcodeproj'


target 'ByteDanceCampus_Klotski' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ByteDanceCampus_Klotski
pod 'AFNetworking', '~> 3.1.0' 
pod 'Masonry', '~> 1.1.0'

end
